services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xtyres-backend-app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - .env
    ports:
      - '8000:8000'
      - '5173:5173'
    volumes:
      - .:/var/www/html
      - backend_vendor:/var/www/html/vendor
      - backend_node_modules:/var/www/html/node_modules
    command:
      - sh
      - docker/start.sh

volumes:
  backend_vendor:
  backend_node_modules:
